[pytest]
testpaths = tests
python_files = test_*.py
python_classes = *Test
python_functions = test_*
addopts = -v -s --doctest-modules --strict-markers
markers =
    unit: mark a test as a unit test
    integration: mark a test as an integration test
    auth: mark tests related to authentication